name: ListHome
version: ${project.version}
main: com.nekozouneko.listHome.ListHome
api-version: '1.21'
author: RunQ
description: SetHomeプラグインにlisthomeコマンドを追加するだけのプラグイン
softdepend:
  - SetHome

commands:
  listhome:
    description: "SetHomeのホーム一覧を表示するコマンド"
